name: PlayerEffects
main: fr.mrflamme26.playereffects.Main
version: 1.0
api-version: 1.16
description: Plugin pour gerer les particules des joueurs
author: MrFlamme26

commands:
  trails:
  
permissions:
  playereffects.*:
    description: Donner toutes les permissions de PlayerEffects
    children:
      playereffects.item: true
      playereffects.effect.totem: true
  -playereffects.*:
    description: Interdire toutes les permissions de PlayerEffects
    children:
      playereffects.item: false
      playereffects.effect.totem: false
  playereffects.item:
    description: Autoriser l'utilisation des effets de particules
    default: op
  playereffects.effect.totem:
    description: Autoriser l'utilisation de l'effet toto
    default: op